import bcrypt from 'bcryptjs'

export const data = {
    users: [
        {
            name: 'Admin',
            email: 'admin@mail.com',
            password: bcrypt.hashSync('123456', 8),
            isAdmin: true,
        },
        {
            name: 'User',
            email: 'user@mail.com',
            password: bcrypt.hashSync('123456', 8),
            isAdmin: false,
        },
    ],
    products: [
        {
            isNew: true,
            name: 'Solid pattern in fashion summer dress',
            category: 'Shirt',
            img: [
                '/images/products/product-details1.jpg',
                '/images/products/product-details2.jpg',
                '/images/products/product-details3.jpg',
                '/images/products/product-details4.jpg',
                '/images/products/product-details5.jpg',
            ],
            stock: 4,
            price: 178,
            discount: 10,
            brand: 'Nike',
            rating: 3,
            numReviews: 7,
            description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book',
        },
        {
            isNew: true,
            name: 'White & blue t-shirt',
            category: 'Shirt',
            img: [
                '/images/products/product-details4.jpg',
                '/images/products/product-details2.jpg',
                '/images/products/product-details3.jpg',
                '/images/products/product-details1.jpg',
                '/images/products/product-details5.jpg',
            ],
            stock: 2,
            price: 250,
            discount: 10,
            brand: 'Infinity',
            rating: 5,
            numReviews: 0,
            description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book',
        },
        {
            isNew: false,
            name: 'Bata shoe',
            category: 'Shoe',
            img: [
                '/images/products/product-details5.jpg',
                '/images/products/product-details2.jpg',
                '/images/products/product-details3.jpg',
                '/images/products/product-details4.jpg',
                '/images/products/product-details1.jpg',
            ],
            stock: 12,
            price: 190,
            discount: 0,
            brand: 'Bata',
            rating: 4,
            numReviews: 12,
            description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book',
        },
        {
            isNew: false,
            name: 'Adiddas black shoe',
            category: 'Shoe',
            img: [
                '/images/products/product-details3.jpg',
                '/images/products/product-details2.jpg',
                '/images/products/product-details1.jpg',
                '/images/products/product-details4.jpg',
                '/images/products/product-details5.jpg',
            ],
            stock: 18,
            price: 360,
            discount: 0,
            brand: 'Adiddas',
            rating: 2,
            numReviews: 8,
            description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book',
        },
        {
            isNew: false,
            name: 'Stripes shirt',
            category: 'Shirt',
            img: [
                '/images/products/product-details2.jpg',
                '/images/products/product-details1.jpg',
                '/images/products/product-details3.jpg',
                '/images/products/product-details5.jpg',
                '/images/products/product-details4.jpg',
            ],
            stock: 1,
            price: 90,
            discount: 10,
            brand: 'Infinity',
            rating: 3,
            numReviews: 10,
            description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book',
        },
        {
            isNew: false,
            name: 'Lacoste Jeans',
            category: 'Jeans',
            img: [
                '/images/products/product-details4.jpg',
                '/images/products/product-details2.jpg',
                '/images/products/product-details3.jpg',
                '/images/products/product-details1.jpg',
                '/images/products/product-details5.jpg',
            ],
            stock: 36,
            price: 120,
            discount: 10,
            brand: 'Lacoste',
            rating: 5,
            numReviews: 7,
            description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book',
        },
    ]
}