export const data = {
    products: [
        {
            id: 1,
            isNew: true,
            name: 'Solid pattern in fashion summer dress',
            category: 'Shirt',
            img: '/images/products/product1.jpg',
            price: 178,
            discount: 10,
            brand: 'Nike',
            rating: 3,
            numReviews: 7,
            description: 'high quality product',
        },
        {
            id: 2,
            isNew: true,
            name: 'White & blue t-shirt',
            category: 'Shirt',
            img: '/images/products/product1.jpg',
            price: 250,
            discount: 10,
            brand: 'Infinity',
            rating: 5,
            numReviews: 0,
            description: 'high quality product',
        },
        {
            id: 3,
            isNew: false,
            name: 'Bata shoe',
            category: 'Shoe',
            img: '/images/products/product1.jpg',
            price: 190,
            discount: 0,
            brand: 'Bata',
            rating: 4,
            numReviews: 12,
            description: 'high quality product',
        },
        {
            id: 4,
            isNew: false,
            name: 'Adiddas black shoe',
            category: 'Shoe',
            img: '/images/products/product1.jpg',
            price: 360,
            discount: 0,
            brand: 'Adiddas',
            rating: 2,
            numReviews: 8,
            description: 'high quality product',
        },
        {
            id: 5,
            isNew: false,
            name: 'Stripes shirt',
            category: 'Shirt',
            img: '/images/products/product1.jpg',
            price: 90,
            discount: 10,
            brand: 'Infinity',
            rating: 3,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            id: 6,
            isNew: false,
            name: 'Lacoste Jeans',
            category: 'Jeans',
            img: '/images/products/product1.jpg',
            price: 120,
            discount: 10,
            brand: 'Lacoste',
            rating: 5,
            numReviews: 7,
            description: 'high quality product',
        },
    ]
}